In [1]:
include("quantum.jl")
using LinearAlgebra
Grid(a::Vector, b::Vector) = collect(Iterators.product(a, b))

Grid (generic function with 1 method)

In [2]:
# define sic povm projectors
ψ₀ = Ket([1,0])
ψ₁ = Ket([1/sqrt(3), sqrt(2/3)])
ψ₂ = 1/sqrt(3) * Ket([1, sqrt(2)*exp(2*pi*im/3)])
ψ₃ = 1/sqrt(3) * Ket([1, sqrt(2)*exp(4*pi*im/3)])

Ket{2}(ComplexF64[0.5773502691896258 + 0.0im, -0.40824829046386346 - 0.7071067811865476im])

In [27]:
bs = BlochSphere()
push!(bs, rand(Ket{2}))
plot(bs)

In [3]:
# define projectors orthogonal to sic povm projectors
ϕ₀ = Ket([0,1])
ϕ₁ = 1/sqrt(3) * Ket([sqrt(2), -1])
ϕ₂ = 1/sqrt(3) * Ket([-sqrt(2), exp(2*pi*im/3)])
ϕ₃ = 1/sqrt(3) * Ket([sqrt(2), exp(pi*im/3)])

Ket{2}(ComplexF64[0.8164965809277261 + 0.0im, 0.288675134594813 + 0.5im])

In [6]:
# ensure orthogonality
@assert isapprox(inner(ϕ₀,ψ₀), 0, atol=1e-15) 
@assert isapprox(inner(ϕ₁,ψ₁), 0, atol=1e-15)
@assert isapprox(inner(ϕ₂,ψ₂), 0, atol=1e-15)
@assert isapprox(inner(ϕ₃,ψ₃), 0, atol=1e-15)

In [122]:
data(π₂)

2×2 Matrix{ComplexF64}:
  0.333333+0.0im       -0.235702-0.408248im
 -0.235702+0.408248im   0.666667+0.0im

In [131]:
rank(permutedims(hcat([reshape(data(Π), 16) for Π in Πs]...)))

16

In [3]:
# define new projectors
π₀ = outer(ψ₀) 
π₁ = outer(ψ₁) 
π₂ = outer(ψ₂) 
π₃ = outer(ψ₃)
πs = [π₀, π₁, π₂, π₃]

4-element Vector{Operator{2}}:
 Operator{2}(ComplexF64[1.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im])
 Operator{2}(ComplexF64[0.3333333333333334 + 0.0im 0.47140452079103173 + 0.0im; 0.47140452079103173 + 0.0im 0.6666666666666666 + 0.0im])
 Operator{2}(ComplexF64[0.3333333333333334 + 0.0im -0.2357022603955158 - 0.4082482904638632im; -0.2357022603955158 + 0.4082482904638632im 0.6666666666666667 + 0.0im])
 Operator{2}(ComplexF64[0.3333333333333334 + 0.0im -0.23570226039551612 + 0.4082482904638631im; -0.23570226039551612 - 0.4082482904638631im 0.6666666666666672 + 0.0im])

In [30]:
ρ̂ = density(rand(Ket{2}))
ms  = 1/2 * [tr(ρ̂*π) for π in πs]
ρ̂ᵣ = 3 * sum([π*m for (π, m) in zip(πs, ms)]) - Operator([1 0; 0 1])
fidelity(ρ̂ᵣ, ρ̂)

1.0000000000000013

In [198]:
sum(Πs)

Operator{4}(ComplexF64[4.000000000000002 + 0.0im -3.608224830031759e-16 - 1.942890293094024e-16im -3.0531133177191805e-16 - 2.220446049250313e-16im 1.3877787807814457e-17 + 2.7755575615628914e-17im; -3.608224830031759e-16 + 1.942890293094024e-16im 4.000000000000002 + 0.0im -5.551115123125783e-17 + 0.0im -3.608224830031759e-16 - 2.7755575615628914e-16im; -3.0531133177191805e-16 + 2.220446049250313e-16im -5.551115123125783e-17 + 0.0im 4.000000000000001 + 0.0im -3.608224830031759e-16 - 3.3306690738754696e-16im; 1.3877787807814457e-17 - 2.7755575615628914e-17im -3.608224830031759e-16 + 2.7755575615628914e-16im -3.608224830031759e-16 + 3.3306690738754696e-16im 4.000000000000002 + 0.0im])

In [15]:
matrices = [kron(πs[i],πs[j]) for i in eachindex(πs) for j in eachindex(πs)];

In [55]:
ρ̂ = density(Ket([1,0,0,0]))
ms = [tr(ρ̂*m)*m for m in matrices]

16-element Vector{Operator{4}}:
 Operator{4}(ComplexF64[1.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im])
 Operator{4}(ComplexF64[0.11111111111111117 + 0.0im 0.1571348402636773 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.1571348402636773 + 0.0im 0.22222222222222227 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im])
 Operator{4}(ComplexF64[0.11111111111111117 + 0.0im -0.07856742013183862 - 0.13608276348795442im 0.0 + 0.0im 0.0 + 0.0im; -0.07856742013183862 + 0.13608276348795442im 0.22222222222222232 + 0.0im -0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im 0.0 + 0.0im; -0.0 + 0.0im 0.0 + 0.0im -0.0 + 0.0im 0.0 + 0.0im])
 Operator{4}(ComplexF64[0.11111111111111117 + 0.0im -0.07856742013183873 + 0.1360827634879544im 0.0 + 0.0im -0.0 + 0.0im; -0.07856742013183873

In [61]:
display(round.(data(sum(ms))))

4×4 Matrix{ComplexF64}:
  2.0+0.0im  -0.0-0.0im  -0.0-0.0im  -0.0+0.0im
 -0.0+0.0im   1.0+0.0im  -0.0+0.0im  -0.0-0.0im
 -0.0+0.0im  -0.0+0.0im   1.0+0.0im  -0.0-0.0im
 -0.0-0.0im  -0.0+0.0im  -0.0+0.0im   0.0+0.0im

In [23]:
reshape(data(π₂), 4)

4-element Vector{ComplexF64}:
  0.3333333333333334 + 0.0im
 -0.2357022603955158 + 0.4082482904638632im
 -0.2357022603955158 - 0.4082482904638632im
  0.6666666666666667 + 0.0im

In [14]:
display(data(kron(π₁, π₀)))

4×4 Matrix{ComplexF64}:
 0.333333+0.0im  0.0+0.0im  0.471405+0.0im  0.0+0.0im
      0.0+0.0im  0.0+0.0im       0.0+0.0im  0.0+0.0im
 0.471405+0.0im  0.0+0.0im  0.666667+0.0im  0.0+0.0im
      0.0+0.0im  0.0+0.0im       0.0+0.0im  0.0+0.0im

In [6]:
ρ̂ = density(Ket([1,0,0,0]))
ms  = [tr((matrix/tr(matrix)) * ρ̂) for matrix in matrices]
ρ̂ᵣ = sum([m * (Operator(diagm([1/4, 1/4, 1/4, 1/4])) * matrix) for (matrix, m) in zip(matrices, ms)]) # - Operator([1 0 0 0 ; 0 1 0 0; 0 0 1 0; 0 0 0 1])

Operator{4}(ComplexF64[0.44444444444444464 + 0.0im 5.204170427930421e-18 - 3.469446951953614e-17im 4.336808689942018e-19 - 3.426078865054194e-17im 8.673617379884035e-19 + 8.673617379884035e-19im; 5.204170427930421e-18 + 3.469446951953614e-17im 0.22222222222222227 + 0.0im -1.734723475976807e-18 + 0.0im 3.469446951953614e-18 - 1.8214596497756474e-17im; 4.336808689942018e-19 + 3.426078865054194e-17im -1.734723475976807e-18 + 0.0im 0.22222222222222227 + 0.0im 3.469446951953614e-18 - 1.9081958235744878e-17im; 8.673617379884035e-19 - 8.673617379884035e-19im 3.469446951953614e-18 + 1.8214596497756474e-17im 3.469446951953614e-18 + 1.9081958235744878e-17im 0.11111111111111119 + 0.0im])

In [16]:
Πs = [kron(πs[i], πs[j]) for i in 1:4 for j in 1:4];

In [27]:
repetitions = 1_000_000
true_states = rand(Ket{4}, repetitions)
estimate_states = rand(Ket{4}, repetitions)
fids = map(i -> estimate_fidelity(density(true_states[i]), density(estimate_states[i]), Πs), eachindex(estimate_states));
fids_pauli = map(i -> estimate_fidelity(density(true_states[i]), density(estimate_states[i]), paulimatrices(4)), eachindex(estimate_states));

In [32]:
f = Figure()
ax = Axis(f[1,1])
hist!(ax, fids .* 2.25, bins=50)
hist!(ax, fids_pauli, bins=50)
f

In [8]:
# check that matrices are unitary
@assert isapprox(data(π₀' * π₀), [1 0; 0 1], atol=1e-10) "$(data(π₀' * π₀))"
@assert isapprox(data(π₁' * π₁), [1 0; 0 1], atol=1e-10) "$(data(π₁' * π₁))"
@assert isapprox(data(π₂' * π₂), [1 0; 0 1], atol=1e-10) "$(data(π₂' * π₂))"
@assert isapprox(data(π₃' * π₃), [1 0; 0 1], atol=1e-10) "$(data(π₃' * π₃))"

In [141]:
[tr(πs[i] * πs[j]) for i in eachindex(πs), j in eachindex(πs)][4, :]

4-element Vector{ComplexF64}:
  0.3333333333333334 + 0.0im
 0.33333333333333337 + 0.0im
  0.3333333333333337 + 0.0im
   1.000000000000001 + 0.0im

In [136]:
# use πs for reconstruction of quantum state
state = Ket([1,0, 0, 0])
ms = 1/2 * map(π -> expectation(state, π), sicpovm_matrices)
data(sum(i -> ms[i] * povm[i], eachindex(ms)))

UndefVarError: UndefVarError: `povm` not defined

# Testing Quantum State Tomography with SIC-POVM

In [2]:
# define sic povm projectors
ψ₀ = Ket([1,0])
ψ₁ = Ket([1/sqrt(3), sqrt(2/3)])
ψ₂ = 1/sqrt(3) * Ket([1, sqrt(2)*exp(2*pi*im/3)])
ψ₃ = 1/sqrt(3) * Ket([1, sqrt(2)*exp(4*pi*im/3)])

Ket{2}(ComplexF64[0.5773502691896258 + 0.0im, -0.40824829046386346 - 0.7071067811865476im])

In [3]:
# define sic povm projection operators
π₀ = outer(ψ₀)
π₁ = outer(ψ₁)
π₂ = outer(ψ₂)
π₃ = outer(ψ₃)
πs = [π₀, π₁, π₂, π₃];

In [4]:
# define dual frame operators
f₀ = Operator([2 0; 0 -1])
f₁ = Operator([0 sqrt(2); sqrt(2) 1])
f₂ = Operator([0 -(1+im*sqrt(3))/sqrt(2); -(1-im*sqrt(3)) 1])
f₃ = Operator([0 -(1-im*sqrt(3))/sqrt(2); -(1+im*sqrt(3)) 1])
fs = [f₀, f₁, f₂, f₃];

In [15]:
Πs = [kron(πs[i], πs[j]) for i in 1:4 for j in 1:4];

In [202]:
function povm_estimate(ρ̂::Operator{4}, σ̂::Operator{4}, Πs::Array{Operator{4},1}, Fs::Array{Operator{4},1})
    @assert length(Πs) == length(Fs)
    ms_rho, ms_sigma = 1/4 * [tr(Π*ρ̂) for Π in Πs] , 1/4 * [tr(Π*σ̂) for Π in Πs]
    ρ_sum = real(data(sum((m_rho*F) for (m_rho, F) in zip(ms_rho, Fs))))
    σ_sum = real(data(sum((m_sigma*F) for (m_sigma, F) in zip(ms_sigma, Fs))))
    sum(abs, diag(ρ_sum) .- diag(σ_sum))
end

povm_estimate (generic function with 1 method)

In [203]:
function experiment()
    fids = map(1:1_000_000) do _
        ρ̂ = density(rand(Ket{4}))
        σ̂ = density(rand(Ket{4}))
        povm_estimate(ρ̂, σ̂, Πs, Fs)
    end
    println(mean(fids), maximum(fids), minimum(fids))
    fids
end

experiment (generic function with 1 method)

In [127]:
# given random state - two qubit
ρ̂ = density(rand(Ket{4}))

# measure the state using povm projectors
ms = 1/4 * real([tr(Π*ρ̂) for Π in Πs])

# reconstruct the state using dual frame operators
ρ̂ᵣ = sum([m*F for (m, F) in zip(ms, Fs)])
sum([(v1-v2)^2 for (v1, v2) in zip(diag(data(ρ̂)), diag(data(ρ̂ᵣ)))])

2.0029671421627253e-32 + 0.0im

In [201]:
state = density(rand(Ket{4}))
other = density(rand(Ket{4}))
povm_estimate(state, other, Πs, Fs)

0.12933510214005156

In [204]:
hist(experiment(), bins=50)

0.6604696665238451.95355150182849260.007240928135851657


In [216]:
function new_sgqt_walk(ρ̂::Operator{4}, ϕ::Ket{4}, i::Int, paramsᵦ::NamedTuple, paramsᵧ::NamedTuple)
    Δᵢ = rand(Ket{4})
    indices = sample(1:16, 8, replace=false)
    βᵢ = β(i; paramsᵦ...)
    γᵢ = γ(i; paramsᵧ...)

    σ̂₊, σ̂₋ = normalize!(density(ϕ + (Δᵢ*βᵢ))), normalize!(density(ϕ - (Δᵢ*βᵢ)))
    F̃₊, F̃₋ = povm_estimate(ρ̂, σ̂₊, Πs[indices], Fs[indices]), povm_estimate(ρ̂, σ̂₋, Πs[indices], Fs[indices])
    gᵢ = -(F̃₊ - F̃₋)/2βᵢ
    return normalize(ϕ + γᵢ*gᵢ*Δᵢ)
end

function new_sgqt(ρ̂::Operator{4}, iterations::Int; paramsᵦ::NamedTuple=(;b=0.4, t=1/6), paramsᵧ::NamedTuple=(;a=55.0, A=0.0, s=1.0))
    ϕᵢ = rand(Ket{4})
    ψs = Ket{4}[ϕᵢ]
    for i in 1:iterations
        push!(ψs, ϕᵢ)
        ϕᵢ = new_sgqt_walk(ρ̂, ϕᵢ, i, paramsᵦ, paramsᵧ)
    end
    ψs
end

new_sgqt (generic function with 1 method)

In [217]:
# Compute the mean fidelity of the estimate of the algorithm after a given number of iterations
function mean_fidelity(repetitions::Int, paramsᵧ::NamedTuple, paramsᵦ::NamedTuple; iterations::Int=100)
    mean(1:repetitions) do _
        ϕ = rand(Ket{4}) 
        fidelity(ϕ, new_sgqt(density(ϕ), iterations; paramsᵦ=paramsᵦ, paramsᵧ=paramsᵧ)[end])
    end    
end

# Define function that calculates the mean fidelity of the algorithm after a given number of iterations
function gridsearch(iterations::Int, repetitions::Int; grid::Matrix{Tuple{NamedTuple{(:a,), Tuple{Float64}}, NamedTuple{(:b,), Tuple{Float64}}}})
    fidelities = map(params -> mean_fidelity(repetitions, params[1], params[2]; iterations=iterations), grid) 
    value, index  = findmax(fidelities)    
    return fidelities, (value, grid[index]...)
end

# Calculate fidelities of estimates of algorithm using best parameters
function estimate_fidelities(iterations::Int; paramsᵦ::NamedTuple,  paramsᵧ::NamedTuple, repetitions::Int=100)
    fidelities  = zeros(repetitions, iterations+1)
    foreach(1:repetitions) do index
        ϕ = rand(Ket{4}) 
        ψs = new_sgqt(density(ϕ), iterations, paramsᵦ=paramsᵦ, paramsᵧ=paramsᵧ)
        fidelities[index, :] .= map(ψ -> fidelity(ψ, ϕ), ψs)
    end
    vec(mean(fidelities, dims=1)), vec(std(fidelities, dims=1));
end

estimate_fidelities (generic function with 1 method)

In [229]:
# Define ranges for parameters
a_range =  range(20, 40, length=20)
b_range =  range(0.4, 0.6, length=20)

# Create named tuples
alphas = map(a -> (; a=a), a_range)
betas = map(b -> (; b=b), b_range)

# Create grid of named tuples
grid = Grid(alphas, betas)

# Perform grid search
fids, (value, best_alpha, best_beta) = gridsearch(100, 500; grid=grid)
value, best_alpha, best_beta

(0.9246814428996328, (a = 29.473684210526315,), (b = 0.5684210526315789,))

In [228]:
μ, σ =  estimate_fidelities(100, paramsᵦ=best_beta, paramsᵧ=best_alpha)

f = Figure()
ax = Axis(f[1,1])
band!(ax, 0:100, μ-σ, μ+σ, fillalpha=0.3, label="SGQT")
lines!(ax, 0:100, μ, label="SGQT")
f